### PR TITLE
Leetcode cpp questions

### PR DESCRIPTION
**Pull request by shubhtoy**
For hacktoberfest 2022

### CODE REVIEW

**Comment by shubhtoy** [comment]
Kindly add the accepted label, it's rejected on dashboard.

**Comment by anwesh08** [comment]
> Kindly add the accepted label, it's rejected on dashboard.

@shubhtoy Hacktober-accepted

**Comment by shubhtoy** [comment]
please make the label to be "hacktoberfest-accepted"

**Comment by anwesh08** [comment]
I have added the accepted label...

**Comment by shubhtoy** [comment]
Thanks!

**Pull request merged**
